### ISSUE TITLE
RE7 Refuses to render to the Index or respond to inputs. Previously will work, no system changes in between sessions.

### ISSUE THREAD

**Issue by optimumbox** [praydog/REFramework#329] opened 2022-05-18 18:51 UTC
I'm having an issue where the game refuses to work anymore in my Index. I played through earlier today with no issues, during my second play through the game refused to hook on launch displaying only the steamvr mountain background. I've tried full restarts, reinstalled the mod, turning off my monitor, but nothing works. The issue is not on my system or headset's end as I'm able to load up everything else in my library just fine.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/8719440/re2_framework_log.txt)

**Comment by praydog** [comment] 2022-05-25 15:45
The issue is the backbuffer format that was created for the game when you launched it was  10 (`DXGI_FORMAT_R16G16B16A16_FLOAT`), most likely indicating a monitor setting was changed.

The correct format needs to be 28 or 29 (`DXGI_FORMAT_R8G8B8A8_UNORM` or `DXGI_FORMAT_R8G8B8A8_UNORM_SRGB`)

The line in the log that gives it away is `[2022-05-18 14:42:23.339] [REFramework] [info] [D3D11] Back buffer format is 10`

I recognize that this is an issue for people with HDR monitors or monitors that can generally just output wider color ranges. My monitor isn't the newest of monitors, but I'll see if there's anything I can do on my end to mitigate the issue.

**Comment by optimumbox** [comment] 2022-05-25 18:59
First, I want to thank you for looking at it and responding. I ended up finding a weird fix that worked for me and another user here: https://github.com/praydog/REFramework/issues/324#issuecomment-1131753180. I basically covered the sensor that detects if the headset is being worn with tape and the issue went away completely. Originally I had tried unplugging my monitor, etc, and that had no effect.

**Comment by boogje** [comment] 2022-06-08 11:21
Bump. New user here, can confirm both the problem and the workaround.
Problem: game loads, but displays black screen/environment in index HMD. 
On monitor, results differ depending on using Steamvr or openXR. Completely black screen with steamvr, but with openxr (renaming the dll file) the monitor displays the vr environment as it should be in the headset, tracking and all. Confirming that the game is not hanging, but just refusing to render in the HMD. 
Workaround: covering the sensor solves this issue, game displays correctly in HMD.

**Comment by mamefan** [comment] 2022-06-08 11:34
This happened to me after buying the RE7 DLC. I had to verify my game files in steam to get it working.

**Comment by praydog** [comment] 2022-06-24 05:53
Might be fixed with 6ec78be9a17d7cc890d2039ffcfa87fcac3040b9

Re-open the issue if it's not.

**Closed by praydog** 2022-06-24 05:53 UTC
