### ISSUE TITLE
RE4 crashed in latest REFramework

### ISSUE THREAD

**Issue by xielu314** [praydog/REFramework#912] opened 2023-10-03 04:41 UTC
**Description**
I re-installed RE4 and tried the latest stable(v1.5.2) and newer(v1.585-) REFramework, but it just crashed after the animation of RE Engine showed.I only dropped dinput8.dll into the game folder.

**Log files**
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/12788511/re2_framework_log.txt)
[reframework_crash.txt](https://github.com/praydog/REFramework/files/12788521/reframework_crash.txt)
I changed reframework_crash.dmp to txt due to dmp files cannot be uploaded to github.Besides,I noticed that the log file was named as **re2**_framework_log.txt, but I definiteily downloaded the **RE4**.zip.

**Identify the REFramework version**
9f479eae9c017763d9e33822fa323644576b5dfa
According to reframework_revision.txt.

**Desktop and VR:**
 - OS: Windows 10
 - Graphics card: RTX 3070ti
 - CPU: AMD Ryzen 7 5800X
 - No VR

**Comment by praydog** [comment] 2023-10-03 06:59
Are you using the Japanese version of the game, a cracked copy, or some other international version of the game?

**Comment by xielu314** [comment] 2023-10-03 07:58
> Are you using the Japanese version of the game, a cracked copy, or some other international version of the game?

Yes. I am playing the Japanese version. Does it matter? If it matters, how to fix?

**Comment by praydog** [comment] 2023-10-03 11:15
Yeah, it matters. The japanese copy has slightly different code in regards to the integrity checks they are performing, and sometimes it can't find it to patch it out. I had fixed this very recently actually, but it sounds like the issue is occurring again.

**Comment by xielu314** [comment] 2023-10-04 00:00
Alright. I think I can only wait for your good news.

**Comment by praydog** [comment] 2023-10-04 08:43
Should be fixed in d7655f0389fe5a88f4dd2794b923db9e94836c80

Download the latest nightly release from [here](https://github.com/praydog/REFramework-nightly/releases/) and let me know if it works.

**Comment by xielu314** [comment] 2023-10-04 11:07
It works! Thanks for your help.

**Closed** 2023-10-04 14:59 UTC

**Comment by keitafromjpn** [comment] 2023-10-04 22:57
> Should be fixed in [d7655f0](https://github.com/praydog/REFramework/commit/d7655f0389fe5a88f4dd2794b923db9e94836c80)
> 
> Download the latest nightly release from [here](https://github.com/praydog/REFramework-nightly/releases/) and let me know if it works.

It works for me as well with Japanese version. Thank you
