### ISSUE TITLE
RE8 strange spherical view inside headset

### ISSUE THREAD

**Issue by mamefan** [praydog/REFramework#125] opened 2022-01-03 00:18 UTC
It's like the game is a screen wrapped around me 360 degrees. It moves with my head movements and is unplayable. Played it last night without issue and didn't change any settings. Tried today, and this issue. Tried reinstalling the mod and game and different in-game display settings. Changing it to windowed or full screen will fix it until I exit options. Then it goes back to the sphere. I do not have an HDR monitor.

**Comment by Marirarius89** [comment] 2022-01-03 13:22
I have found that what works for me is: unplug monitor when starting the game. The game shows in headset but is stretched out. I start the game from the main menu, and when in the game I plug my monitor back in. If nothing happens I minimize the game screen on my desktop, wait a second, and bring it back into view. This pauses the game. The game looks like a proper VR game in the headset.

**Comment by mamefan** [comment] 2022-01-03 20:03
Thank you, that worked! Looks like I have to unplug and replug my monitor at the title screen every time I play it until the issue is fixed.

**Comment by g-coded** [comment] 2022-01-04 03:34
I'm getting something similar after entering the settings menu.

**Comment by mamefan** [comment] 2022-01-05 12:58
Last night, the monitor cable unplug/replug thing didn't work, but minimizing and then restoring the game window did work.

**Comment by Tatil7** [comment] 2022-01-08 17:07
Hello, i have the same display issue. It worked perfectly at the beginning and when I restarted the game the image is like stretching vertically in windowed mode.
 I tried in full screen mode but now the image is compressed with black bands.  it's completely unplayable. 
  I have a laptop, it's going to be hard to unplug the screen 😅 I've tried everything, uninstall the Nvidia drivers, uninstall the game, change the nvidia settings ... nothing helps.  do you know where the problem is?

**Comment by Marirarius89** [comment] 2022-01-08 18:57
> Hello, i have the same display issue. It worked perfectly at the beginning and when I restarted the game the image is like stretching vertically in windowed mode. I tried in full screen mode but now the image is compressed with black bands. it's completely unplayable. I have a laptop, it's going to be hard to unplug the screen 😅 I've tried everything, uninstall the Nvidia drivers, uninstall the game, change the nvidia settings ... nothing helps. do you know where the problem is?

Have you tried minimizing the game and resizing again? That often works for me.

**Comment by iiStryker** [comment] 2022-01-13 04:04
moving the steam vr resolution slider fixes this issue for me.

**Comment by Marirarius89** [comment] 2022-01-15 18:16
Nice! Thank you. That trick solved it much better for me

**Comment by praydog** [comment] 2022-03-16 22:36
Fixed in 263ac372cb2fbbcdcae8db17ccad7d40d20c1e41

**Closed by praydog** 2022-03-16 22:36 UTC
