### ISSUE TITLE
Startup crash on DD2

### ISSUE THREAD

**Issue by makotech222** [praydog/REFramework#1010] opened 2024-03-22 15:48 UTC
**Describe the bug**
Just a regular crash on startup for DD2, using latest nightly build

**Upload logs and any crash dumps**
[reframework_crash.dmp](https://github.com/praydog/REFramework/files/14724959/reframework_crash.dmp)
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14724960/re2_framework_log.txt)

**Identify the REFramework version**
REF Nightly 669 

**To Reproduce**
Copy reframework (with no xr/vr) to DD2 folder. Start up DD2.

**Desktop and VR (please complete the following information):**
Win 11, no VR

**Comment by praydog** [comment] 2024-03-22 16:38
I am aware, looking into the issue.

**Comment by Lastu1991** [comment] 2024-03-23 06:39
Just writeing to upload my crash files incase it could help ya all findeing the cause for it.
Same version and behavior of the crash then OP.

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14730509/re2_framework_log.txt)
[reframework_crash.dmp](https://github.com/praydog/REFramework/files/14730510/reframework_crash.dmp)

**Comment by praydog** [comment] 2024-03-23 06:41
The anti-tamper is pretty annoying to deal with in this one, a bit worse than the previous RE Engine games, which is what's causing the crash. I'll continue to investigate.

**Comment by praydog** [comment] 2024-03-24 00:32
Fixed in f9aeefd432e255cb29fd04b9b9a1c0b790c65746

Nightly builds can be downloaded from https://github.com/praydog/REFramework-nightly/releases/

If your crashes are still occurring, open a new issue or re-open this one.

**Comment by Foul-Tarnished** [comment] 2024-03-24 00:38
> Fixed in [f9aeefd](https://github.com/praydog/REFramework/commit/f9aeefd432e255cb29fd04b9b9a1c0b790c65746)
> 
> Nightly builds can be downloaded from https://github.com/praydog/REFramework-nightly/releases/
> 
> If your crashes are still occurring, open a new issue or re-open this one.

[re2_framework_log.txt](https://github.com/pray
[reframework_crash.dmp](https://github.com/praydog/REFramework/files/14733982/reframework_crash.dmp)
dog/REFramework/files/14733981/re2_framework_log.txt)

Game crash at startup
(btw I use DSR 4x, but desktop is and ingame are both set at dsr resolution anyway)

**Comment by makotech222** [comment] 2024-03-24 00:39
Same, got crash
[reframework_crash.dmp](https://github.com/praydog/REFramework/files/14733985/reframework_crash.dmp)
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14733986/re2_framework_log.txt)

**Comment by makotech222** [comment] 2024-03-24 01:13
New ones for build 673.

Greatly appreciate your support and your work on this app!
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14734033/re2_framework_log.txt)

[reframework_crash.dmp](https://github.com/praydog/REFramework/files/14734032/reframework_crash.dmp)

**Comment by LeonNamowitz** [comment] 2024-03-24 01:42
Here as well.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14734081/re2_framework_log.txt)
[reframework_crash.dmp](https://github.com/praydog/REFramework/files/14734082/reframework_crash.dmp)

**Comment by praydog** [comment] 2024-03-24 02:22
Was able to get the crash to occur on my i9 laptop. Cannot get it to occur on my 7950x3D machine. So will continue development trying to fix the issue there.

To clarify, I *did* fix a crash that was occurring after this, this just happened to not be the same crash.

**Comment by TheDarkFleet** [comment] 2024-03-24 02:40
> Was able to get the crash to occur on my i9 laptop. Cannot get it to occur on my 7950x3D machine. So will continue development trying to fix the issue there.
> 
> To clarify, I _did_ fix a crash that was occurring after this, this just happened to not be the same crash.

logs from 7950x3d 7900xtx

**Comment by TheDarkFleet** [comment] 2024-03-24 02:40
> Was able to get the crash to occur on my i9 laptop. Cannot get it to occur on my 7950x3D machine. So will continue development trying to fix the issue there.
> 
> To clarify, I _did_ fix a crash that was occurring after this, this just happened to not be the same crash.

logs from 7950x3d and 7900xtx
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14734193/re2_framework_log.txt)
[reframework_crash.dmp](https://github.com/praydog/REFramework/files/14734194/reframework_crash.dmp)

**Comment by praydog** [comment] 2024-03-24 03:00
Fixed in 41f927bb3841bd9d1143ced79c81e0a888eb620c, confirmed by multiple users in the Modding Haven Discord.

Nightly builds: https://github.com/praydog/REFramework-nightly/releases/

**Closed by praydog** 2024-03-24 03:00 UTC

**Comment by TheDarkFleet** [comment] 2024-03-24 03:02
Sure is. Legend

**Comment by makotech222** [comment] 2024-03-24 03:21
Yep, 674 is working for me. Thank you so much!
